global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:5003']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5004']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:5002']

  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:5001']

  - job_name: 'shipping-service'
    static_configs:
      - targets: ['shipping-service:5005']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5006']
