apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: ecommerce-services
data:
  FLASK_ENV: "development"
  RABBITMQ_HOST: "rabbitmq.ecommerce-infra.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  # Service URLs (for cross-service communication)
  ORDER_SERVICE_URL: "http://order-service:5003"
  INVENTORY_SERVICE_URL: "http://inventory-service:5002"
  PAYMENT_SERVICE_URL: "http://payment-service:5004"
  CUSTOMER_SERVICE_URL: "http://customer-service:5001"
  SHIPPING_SERVICE_URL: "http://shipping-service:5005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5006"
